name: Fine
main: com.allenvox.fine.Plugin
version: 1.0.0
api-version: 1.19.2
author: allenvox
description: A fine plugin for Paper
commands:
  description: Show/save coordinates
  usage: /coords [x] [z] [name]
  aliases: [c]